blank_issues_enabled: false

contact_links:
  - name: ğŸ›¡ï¸ Reporte de Vulnerabilidades de SeguranÃ§a e Suporte
    url: https://github.com/nytheria-team/nytheria/wiki/Reporte-de-Vulnerabilidades-de-Seguran%C3%A7a-e-Suporte
    about: Reporte vulnerabilidades de seguranÃ§a e solicite suporte tÃ©cnico aqui.
